export const OPEN_PANEL = 'OPEN_PANEL'
export const CLOSE_PANEL = 'CLOSE_PANEL'
export const SET_PANEL_PROP = 'SET_PANEL_PROP'
export const SET_PANEL_PLACEHOLDER = 'SET_PANEL_PLACEHOLDER'
export const SET_ACTIVE_PANEL = 'SET_ACTIVE_PANEL'
export const SET_MAINBAR_POSITION = 'SET_MAINBAR_POSITION'
export const SET_IS_ANY_PANEL_DRAGGING = 'SET_IS_ANY_PANEL_DRAGGING'

export const SET_MAINBAR_ORDER = 'SET_MAINBAR_ORDER'
export const SET_PANEL_WIDTH = 'SET_PANEL_WIDTH'
export const SET_PANELS_ORDER = 'SET_PANELS_ORDER'
export const SET_PANEL_POS = 'SET_PANEL_POS'

// Elements
export const SET_INITIAL_PAGE_CONTENT = 'SET_INITIAL_PAGE_CONTENT'
export const SET_VISIBLE_ELEMENTS = 'SET_VISIBLE_ELEMENTS'

export const UPDATE_AREA_CONTENT = 'UPDATE_AREA_CONTENT'
export const SET_ACTIVE_AREA = 'SET_ACTIVE_AREA'
export const COPY_ELEMENT = 'COPY_ELEMENT'
export const DELETE_ELEMENT = 'DELETE_ELEMENT'
export const RENAME_ELEMENT = 'RENAME_ELEMENT'
export const SAVE_SORTING = 'SAVE_SORTING'
export const REGISTER_ELEMENT = 'REGISTER_ELEMENT'

// History
export const HISTORY_ADD = 'HISTORY_ADD'
export const HISTORY_CHANGE_ACTIVE = 'HISTORY_CHANGE_ACTIVE'

// Viewports
export const VIEW_DEVICE = 'VIEW_DEVICE'
export const SET_ACTIVE_DEVICE = 'SET_ACTIVE_DEVICE'

// Preview Frame
export const SET_IFRAME_POINTER_EVENTS = 'SET_IFRAME_POINTER_EVENTS'
export const SET_IFRAME_ORDER = 'SET_IFRAME_ORDER'
export const SET_STYLE_LOADING = 'SET_STYLE_LOADING'
export const SET_MAINBAR_POINTER_EVENTS = 'SET_MAINBAR_POINTER_EVENTS'

// Page content
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT'
export const SET_PAGE_AREAS = 'SET_PAGE_AREAS'
export const UPDATE_ELEMENT_OPTIONS = 'UPDATE_ELEMENT_OPTIONS'
export const DELETE_ELEMENT_OPTION = 'DELETE_ELEMENT_OPTION'
export const ADD_ELEMENT = 'ADD_ELEMENT'
export const ADD_ELEMENTS = 'ADD_ELEMENTS'
export const UPDATE_ELEMENT_OPTION_VALUE = 'UPDATE_ELEMENT_OPTION_VALUE'
export const UPDATE_PAGE_SETTINGS = 'UPDATE_PAGE_SETTINGS'
export const SET_LOCKED_USERINFO = 'SET_LOCKED_USERINFO'
export const TAKE_OVER_POST = 'TAKE_OVER_POST'
export const SET_NONCE = 'SET_NONCE'
export const SAVE_ELEMENTS_ORDER = 'SAVE_ELEMENTS_ORDER'
export const INSERT_ELEMENTS_IN_PARENT = 'INSERT_ELEMENTS_IN_PARENT'
export const SET_RIGHT_CLICK_MENU = 'SET_RIGHT_CLICK_MENU'
export const ATTACH_SLOTS_TO_ELEMENT = 'ATTACH_SLOTS_TO_ELEMENT'
export const SET_ACTIVE_ELEMENT = 'SET_ACTIVE_ELEMENT'
export const MOVE_ELEMENT = 'MOVE_ELEMENT'

// Data sets
export const SET_DATA_SETS = 'SET_DATA_SETS'

// Interactions
export const SET_DRAGGING_STATE = 'SET_DRAGGING_STATE'
export const SET_IS_TOOLBOX_DRAGGING = 'SET_IS_TOOLBOX_DRAGGING'
export const SET_IS_SAVING_PAGE = 'SET_IS_SAVING_PAGE'
export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE'
export const SET_ACTIVE_PSEUDO_SELECTOR = 'SET_ACTIVE_PSEUDO_SELECTOR'
export const SET_NEW_SELECTOR = 'SET_NEW_SELECTOR'
export const DELETE_NEW_SELECTOR = 'DELETE_NEW_SELECTOR'
export const SET_SHOULD_OPEN_ELEMENTS_POPUP = 'SET_SHOULD_OPEN_ELEMENTS_POPUP'
export const SET_ELEMENT_FOCUS = 'SET_ELEMENT_FOCUS'
export const SET_ACTIVE_SHOW_ADD_ELEMENT_POPUP = 'SET_ACTIVE_SHOW_ADD_ELEMENT_POPUP'

// Classes
export const SET_ACTIVE_CSS_CLASS = 'SET_ACTIVE_CSS_CLASS'
export const ADD_CSS_CLASS = 'ADD_CSS_CLASS'
export const REMOVE_CSS_CLASS = 'REMOVE_CSS_CLASS'
export const EDIT_CSS_CLASS = 'EDIT_CSS_CLASS'
export const UPDATE_CSS_CLASS = 'UPDATE_CSS_CLASS'
export const SET_COPIED_CLASSES = 'SET_COPIED_CLASSES'
export const SET_COPIED_ELEMENT = 'SET_COPIED_ELEMENT'
export const SET_CUTTED_ELEMENT = 'SET_CUTTED_ELEMENT'
export const SET_COPIED_ELEMENT_STYLES = 'SET_COPIED_ELEMENT_STYLES'

// Errors
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_NOTICE = 'REMOVE_NOTICE'

// Templates
export const SET_LOCAL_TEMPLATES = 'SET_LOCAL_TEMPLATES'
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const TEMPLATE_SET_LOADED = 'TEMPLATE_SET_LOADED'

// Library
export const SET_ELEMENT_CONFIG_FOR_LIBRARY = 'SET_ELEMENT_CONFIG_FOR_LIBRARY'
export const SET_TEMPLATE_CATEGORIES = 'SET_TEMPLATE_CATEGORIES'
// icons
export const ADD_ICON_SET = 'ADD_ICON_SET'
export const DELETE_ICON_SET = 'DELETE_ICON_SET'
